version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels: [dependencies, python]
    commit-message:
      prefix: "deps(pip)"
    open-pull-requests-limit: 10
    groups:
      python-minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels: [dependencies, ci]
    commit-message:
      prefix: "deps(actions)"
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: "/sdk/node"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels: [dependencies, node]
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels: [dependencies, docker]
    commit-message:
      prefix: "deps(docker)"
