{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisrf.fullname" . }}
  labels:
    {{- include "aisrf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.databaseUrl }}
  AISRF_DATABASE_URL: {{ .Values.databaseUrl | quote }}
  {{- end }}
{{- end }}
