"""NeMo Guardrails (NVIDIA) input and output rails as gateway analyzers.

A RailsConfig is loaded from integrations.nemo_guardrails.config_path or from the bundled default in
airt/guardrails/nemo_default (offline regex actions, no LLM). The LLMRails instance is cached per config
directory and rebuilt when config.yml changes. Only the requested rail type runs
(`options={"rails": ["input"]}` or `["output"]`), so no model is ever generated by NeMo itself; a blocked
message becomes a HIGH finding whose category comes from the flow that fired (jailbreak, injection,
otherwise guardrail). Every check is time-limited (integrations.nemo_guardrails.timeout_seconds, 10s default).
"""
from __future__ import annotations

import asyncio
import os
import threading
import time
from pathlib import Path
from typing import Any

from ..analysis.analyzers.common import make_finding, snippet
from ..analysis.base import Finding, Severity
from ._common import conversation_messages, integration_config, last_error, library_installed, log, log_throttled, primary_text, response_text, set_error

NAME = "nemo_guardrails"
NAME_INPUT = "nemo_guardrails_input"
NAME_OUTPUT = "nemo_guardrails_output"
DEFAULT_CONFIG_DIR = Path(__file__).resolve().parent / "nemo_default"
DEFAULT_TIMEOUT = 10.0
_lock = threading.Lock()
_cache: dict[str, tuple[float, Any]] = {}  # config dir -> (config.yml mtime, LLMRails)


def config_dir(cfg: dict[str, Any] | None = None) -> Path:
    cfg = cfg if cfg is not None else integration_config(NAME)
    raw = str(cfg.get("config_path") or "").strip()
    if raw:
        p = Path(raw).expanduser()
        if not p.is_absolute():
            from ..config import get_settings

            p = Path(get_settings().base_dir) / p
        return p
    return DEFAULT_CONFIG_DIR


def _config_mtime(path: Path) -> float:
    best = 0.0
    try:
        for name in ("config.yml", "config.yaml", "rails.co", "actions.py"):
            f = path / name
            if f.exists():
                best = max(best, f.stat().st_mtime)
    except OSError:
        pass
    return best


def _build_rails(path: Path) -> Any:
    from nemoguardrails import LLMRails, RailsConfig  # noqa: PLC0415  heavy optional dependency

    config = RailsConfig.from_path(str(path))
    return LLMRails(config)


def get_rails(path: Path) -> Any:
    """Return the cached LLMRails for a config directory, building it when missing or stale. Blocking: call in a thread."""
    key = str(path.resolve())
    mtime = _config_mtime(path)
    with _lock:
        entry = _cache.get(key)
        if entry is not None and entry[0] == mtime:
            return entry[1]
        if not path.is_dir():
            raise FileNotFoundError(f"NeMo config directory not found: {path}")
        start = time.perf_counter()
        rails = _build_rails(path)
        _cache[key] = (mtime, rails)
        log.info("guardrails.nemo.loaded", path=key, duration_ms=round((time.perf_counter() - start) * 1000, 1))
        return rails


def _interpret(result: Any) -> dict[str, Any]:
    """Reduce a GenerationResponse (or plain response) to {blocked, flows, exception_type, message}."""
    out: dict[str, Any] = {"blocked": False, "flows": [], "exception_type": "", "message": "", "bot_message": ""}
    response = getattr(result, "response", result)
    if isinstance(response, list):
        for m in response:
            if not isinstance(m, dict):
                continue
            if m.get("role") == "exception":
                content = m.get("content") if isinstance(m.get("content"), dict) else {}
                out["blocked"] = True
                out["exception_type"] = str(content.get("type") or "")
                out["message"] = str(content.get("message") or "")
            elif m.get("role") == "assistant" and isinstance(m.get("content"), str):
                out["bot_message"] = m["content"]
    elif isinstance(response, str):
        out["bot_message"] = response
    log_obj = getattr(result, "log", None)
    for rail in (getattr(log_obj, "activated_rails", None) or []):
        name = str(getattr(rail, "name", "") or "")
        stopped = bool(getattr(rail, "stop", False))
        if name:
            out["flows"].append({"name": name, "stop": stopped, "decisions": list(getattr(rail, "decisions", None) or [])})
        if stopped:
            out["blocked"] = True
    return out


def _category(info: dict[str, Any]) -> tuple[str, list[str]]:
    names = [f["name"] for f in info["flows"] if f.get("stop")] or [info.get("exception_type", "")]
    joined = " ".join(names).lower() + " " + info.get("exception_type", "").lower()
    if "jailbreak" in joined:
        return "jailbreak", names
    if "injection" in joined or "self check input" in joined or "selfcheckinput" in joined:
        return "prompt_injection", names
    if "sensitive" in joined or "pii" in joined:
        return "pii", names
    if "output" in joined:
        return "guardrail", names
    return "guardrail", names


async def run_rails(kind: str, messages: list[dict[str, str]], cfg: dict[str, Any] | None = None) -> dict[str, Any]:
    """Run only the input or output rails of the configured NeMo config on `messages` (time-limited)."""
    cfg = cfg if cfg is not None else integration_config(NAME)
    try:
        timeout = float(cfg.get("timeout_seconds") or DEFAULT_TIMEOUT)
    except (TypeError, ValueError):
        timeout = DEFAULT_TIMEOUT
    path = config_dir(cfg)
    rails = await asyncio.wait_for(asyncio.to_thread(get_rails, path), timeout=max(timeout, 30.0))
    result = await asyncio.wait_for(
        rails.generate_async(messages=messages, options={"rails": [kind], "log": {"activated_rails": True}}),
        timeout=timeout,
    )
    info = _interpret(result)
    info["config_path"] = str(path)
    return info


def _finding(analyzer: str, info: dict[str, Any], text: str, location: str, kind: str) -> Finding:
    category, flows = _category(info)
    flow_label = ", ".join(f for f in flows if f) or "input rail"
    detail = info.get("message") or ""
    return make_finding(
        analyzer, category, Severity.HIGH, f"NeMo Guardrails blocked the {kind} ({flow_label})",
        f"The NeMo Guardrails {kind} rail '{flow_label}' stopped the conversation" + (f": {detail}" if detail else ".") + f" Config: {info.get('config_path', '')}.",
        snippet(text, 0, min(len(text), 120)) if text else "", location, 0.85,
        tags=["nemo_guardrails", kind + "_rail"] + [f.replace(" ", "_") for f in flows if f],
        metadata={"flows": info.get("flows", []), "exception_type": info.get("exception_type", ""), "message": detail, "config_path": info.get("config_path", "")},
    )


class NemoInputAnalyzer:
    name = NAME_INPUT
    description = "Runs the NeMo Guardrails input rails (bundled offline jailbreak and injection heuristics, or a custom config) over the conversation."

    async def analyze(self, normalized: dict[str, Any], context: dict[str, Any]) -> list[Finding]:
        try:
            cfg = integration_config(NAME)
            if not cfg.get("enabled"):
                return []
            if not library_installed("nemoguardrails"):
                set_error(NAME, "nemoguardrails is not installed")
                log_throttled("nemo.missing", "guardrails.nemo.not_installed")
                return []
            messages = conversation_messages(normalized, include_system=bool(cfg.get("include_system", False)))
            if not messages or messages[-1]["role"] != "user":
                text = primary_text(normalized)
                if not text.strip():
                    return []
                messages = [{"role": "user", "content": text}]
            info = await run_rails("input", messages, cfg)
            set_error(NAME, None)
            if not info["blocked"]:
                return []
            return [_finding(self.name, info, messages[-1]["content"], "last_user_message", "input")]
        except Exception as exc:
            set_error(NAME, str(exc))
            log_throttled("nemo.input", "guardrails.nemo.failed", analyzer=self.name, error=str(exc)[:300])
            return []


class NemoOutputAnalyzer:
    name = NAME_OUTPUT
    description = "Runs the NeMo Guardrails output rails over the model response when integrations.nemo_guardrails.run_output_rails is true."

    async def analyze(self, normalized: dict[str, Any], context: dict[str, Any]) -> list[Finding]:
        try:
            cfg = integration_config(NAME)
            if not cfg.get("enabled") or not cfg.get("run_output_rails"):
                return []
            if not library_installed("nemoguardrails"):
                return []
            text = response_text(context)
            if not text.strip():
                return []
            messages = conversation_messages(normalized, include_system=bool(cfg.get("include_system", False)))
            if not messages or messages[-1]["role"] != "user":
                messages.append({"role": "user", "content": primary_text(normalized) or "(no user message)"})
            messages.append({"role": "assistant", "content": text})
            info = await run_rails("output", messages, cfg)
            set_error(NAME, None)
            if not info["blocked"]:
                return []
            return [_finding(self.name, info, text, "response", "output")]
        except Exception as exc:
            set_error(NAME, str(exc))
            log_throttled("nemo.output", "guardrails.nemo.failed", analyzer=self.name, error=str(exc)[:300])
            return []


input_analyzer = NemoInputAnalyzer()
output_analyzer = NemoOutputAnalyzer()


def status() -> dict[str, Any]:
    cfg = integration_config(NAME)
    path = config_dir(cfg)
    installed = library_installed("nemoguardrails")
    has_config = path.is_dir() and any((path / n).exists() for n in ("config.yml", "config.yaml"))
    return {
        "name": NAME,
        "installed": installed,
        "enabled": bool(cfg.get("enabled")),
        "configured": installed and has_config,
        "config_path": str(path),
        "bundled_default": path == DEFAULT_CONFIG_DIR,
        "run_output_rails": bool(cfg.get("run_output_rails")),
        "loaded": str(path.resolve()) in _cache if os.path.isdir(path) else False,
        "analyzers": [NAME_INPUT, NAME_OUTPUT],
        "last_error": last_error(NAME),
    }


async def health_check() -> dict[str, Any]:
    start = time.perf_counter()
    if not library_installed("nemoguardrails"):
        return {"name": NAME, "ok": False, "detail": "nemoguardrails is not installed"}
    try:
        info = await run_rails("input", [{"role": "user", "content": "hello, what is the weather today?"}])
    except Exception as exc:
        return {"name": NAME, "ok": False, "detail": str(exc)[:300], "duration_ms": round((time.perf_counter() - start) * 1000, 1)}
    return {"name": NAME, "ok": not info["blocked"], "detail": f"input rails ran ({len(info['flows'])} flow(s)), benign probe {'blocked' if info['blocked'] else 'passed'}", "duration_ms": round((time.perf_counter() - start) * 1000, 1)}
