"""Desktop mode and per-user application directory for packaged (PyInstaller) builds.

When AISRF runs from a binary, or when ``AISRF_HOME`` is set, state must not land in the current
working directory. This module resolves a per-user application directory, seeds an ``aisrf.env``
file with a random secret key and admin API token on first run, and exports the ``AISRF_*``
environment variables that ``aisrf.config.Settings`` reads. It never edits ``config.py``; every
default is applied through the environment before the settings object is created.

The ``desktop`` CLI command and the ``aisrf-desktop`` console script start the gateway on a free
loopback port in a background thread, wait for ``/healthz`` and open the dashboard in a native
window (pywebview, ``pip install "aisrf[desktop]"``) or in the system browser.
"""

from __future__ import annotations

import contextlib
import os
import secrets
import socket
import stat
import sys
import threading
import time
import webbrowser
from pathlib import Path
from typing import Any

APP_NAME = "AISRF"
ENV_FILE_NAME = "aisrf.env"
GENERATED_KEYS = ("AISRF_SECRET_KEY", "AISRF_ADMIN_API_TOKEN")
_ENV_HEADER = (
    "# Generated by AISRF on first run. Keep this file private: it holds the key that encrypts\n"
    "# stored upstream credentials and the admin API token used by the CLI and the MCP server.\n"
    "# Delete a line to have it regenerated; any AISRF_* setting can be added here.\n"
)


def is_frozen() -> bool:
    """True when running from a PyInstaller bundle."""
    return bool(getattr(sys, "frozen", False)) and hasattr(sys, "_MEIPASS")


def app_dir(platform: str | None = None, env: dict[str, str] | None = None, home: Path | None = None) -> Path:
    """Per-user application directory (platformdirs conventions, without the dependency).

    ``AISRF_HOME`` wins when set. Otherwise: ``%LOCALAPPDATA%\\AISRF`` on Windows,
    ``~/Library/Application Support/AISRF`` on macOS and ``$XDG_DATA_HOME/aisrf`` (default
    ``~/.local/share/aisrf``) elsewhere.
    """
    env = os.environ if env is None else env
    platform = platform or sys.platform
    home = home or Path.home()
    explicit = env.get("AISRF_HOME")
    if explicit:
        return Path(explicit).expanduser()
    if platform.startswith("win"):
        base = env.get("LOCALAPPDATA")
        return (Path(base) if base else home / "AppData" / "Local") / APP_NAME
    if platform == "darwin":
        return home / "Library" / "Application Support" / APP_NAME
    xdg = env.get("XDG_DATA_HOME")
    return (Path(xdg) if xdg else home / ".local" / "share") / APP_NAME.lower()


def default_environment(directory: Path) -> dict[str, str]:
    """AISRF_* values that point data, logs and the SQLite database into ``directory``."""
    data = directory / "data"
    return {
        "AISRF_DATA_DIR": str(data),
        "AISRF_LOG_DIR": str(directory / "logs"),
        "AISRF_DATABASE_URL": f"sqlite+aiosqlite:///{(data / 'aisrf.db').as_posix()}",
    }


def read_env_file(path: Path) -> dict[str, str]:
    """Parse a KEY=VALUE file (comments and blank lines ignored, optional surrounding quotes)."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if key:
            values[key] = value
    return values


def _restrict(path: Path) -> None:
    with contextlib.suppress(OSError):
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def ensure_env_file(directory: Path) -> dict[str, str]:
    """Create ``<directory>/aisrf.env`` with a random secret key and admin token when missing.

    Existing values are preserved, so repeated calls return the same secrets. The file is created
    with mode 0600 on POSIX systems.
    """
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / ENV_FILE_NAME
    values = read_env_file(path)
    missing = [k for k in GENERATED_KEYS if not values.get(k)]
    if missing:
        for key in missing:
            values[key] = secrets.token_urlsafe(48)
        lines = [_ENV_HEADER]
        lines.extend(f"{k}={v}" for k, v in values.items())
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict(path)
    return values


def configure_environment(force: bool = False) -> Path | None:
    """Point the settings at the per-user app directory when frozen, when AISRF_HOME is set or when forced.

    Returns the directory that was applied, or None when running from source without AISRF_HOME.
    Explicit environment variables always win over the generated defaults and the env file.
    """
    if not (force or is_frozen() or os.environ.get("AISRF_HOME")):
        return None
    directory = app_dir()
    directory.mkdir(parents=True, exist_ok=True)
    for key, value in ensure_env_file(directory).items():
        os.environ.setdefault(key, value)
    for key, value in default_environment(directory).items():
        os.environ.setdefault(key, value)
    os.environ.setdefault("AISRF_HOME", str(directory))
    return directory


def free_port(host: str = "127.0.0.1") -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind((host, 0))
        return int(s.getsockname()[1])


def wait_for_health(url: str, timeout: float = 60.0, alive: Any = None) -> bool:
    """Poll ``url`` until it answers 200 or ``timeout`` elapses (``alive()`` False aborts early)."""
    import httpx

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if alive is not None and not alive():
            return False
        try:
            if httpx.get(url, timeout=2.0).status_code == 200:
                return True
        except httpx.HTTPError:
            pass
        time.sleep(0.25)
    return False


class DesktopServer:
    """uvicorn in a daemon thread, bound to the loopback interface."""

    def __init__(self, host: str = "127.0.0.1", port: int | None = None) -> None:
        import uvicorn

        from .config import get_settings

        self.host = host
        self.port = port or free_port(host)
        settings = get_settings()
        config = uvicorn.Config(
            "aisrf.main:create_app",
            factory=True,
            host=self.host,
            port=self.port,
            log_level=settings.log_level.lower(),
            workers=1,
        )
        self.server = uvicorn.Server(config)
        self.thread = threading.Thread(target=self.server.run, name="aisrf-uvicorn", daemon=True)

    @property
    def url(self) -> str:
        return f"http://{self.host}:{self.port}"

    def start(self, timeout: float = 60.0) -> None:
        self.thread.start()
        if not wait_for_health(f"{self.url}/healthz", timeout=timeout, alive=self.thread.is_alive):
            self.stop()
            raise RuntimeError("the gateway did not become healthy; check the log directory for details")

    def stop(self, timeout: float = 15.0) -> None:
        self.server.should_exit = True
        self.thread.join(timeout)
        if self.thread.is_alive():
            self.server.force_exit = True
            self.thread.join(5)


def _open_window(url: str, title: str) -> bool:
    """Show ``url`` in a pywebview window; blocks until it is closed. Returns False when unavailable."""
    try:
        import webview  # type: ignore[import-not-found]
    except Exception:
        return False
    import logging

    logging.getLogger("pywebview").setLevel(logging.CRITICAL)  # it logs a traceback per missing GUI backend
    try:
        webview.create_window(title, url, width=1360, height=880, min_size=(900, 600))
        webview.start()
    except Exception as exc:  # no GTK/Qt/WebView2 runtime; fall back to the browser
        print(f"native window unavailable ({exc.__class__.__name__}: {exc}), opening the browser instead")
        return False
    return True


def run_desktop(port: int | None = None, open_window: bool = True, open_browser: bool = True) -> int:
    """Start the gateway locally and show the dashboard. Returns a process exit code."""
    directory = configure_environment(force=True)
    from .config import get_settings

    settings = get_settings()
    server = DesktopServer(port=port)
    print(f"AISRF {_version()} desktop mode")
    print(f"  app directory : {directory}")
    print(f"  settings file : {Path(directory or '.') / ENV_FILE_NAME}")
    print("  starting the gateway ...", flush=True)
    try:
        server.start()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(f"  dashboard     : {server.url}")
    print(
        f"  sign in as    : {settings.admin_username} / {'admin (change it under Settings)' if settings.admin_password == 'admin' else '<AISRF_ADMIN_PASSWORD>'}"
    )
    print(f"  API token     : AISRF_ADMIN_API_TOKEN in {ENV_FILE_NAME} (for the aisrf CLI and MCP)")
    print("  press Ctrl+C to stop", flush=True)
    code = 0
    _install_signal_handlers()
    try:
        shown = _open_window(server.url, f"{settings.app_name} {_version()}") if open_window else False
        if not shown:
            if open_browser:
                with contextlib.suppress(Exception):
                    webbrowser.open(server.url)
            while server.thread.is_alive():
                time.sleep(0.5)
            if not server.server.should_exit:
                print("the gateway stopped unexpectedly", file=sys.stderr)
                code = 1
    except KeyboardInterrupt:
        print("\nstopping ...")
    finally:
        server.stop()
    print("gateway stopped")
    return code


def _install_signal_handlers() -> None:
    """Turn SIGTERM (and SIGINT when it was left ignored by a parent) into KeyboardInterrupt."""
    import signal

    if threading.current_thread() is not threading.main_thread():
        return

    def _raise(signum: int, _frame: Any) -> None:
        raise KeyboardInterrupt

    for name in ("SIGINT", "SIGTERM", "SIGBREAK"):
        sig = getattr(signal, name, None)
        if sig is not None:
            with contextlib.suppress(Exception):
                signal.signal(sig, _raise)


def _version() -> str:
    from . import __version__

    return __version__


def main() -> None:
    """Console script entry point (``aisrf-desktop``): same as ``aisrf desktop``."""
    port: int | None = None
    open_window = True
    open_browser = True
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        arg = args[i]
        if arg in {"-h", "--help"}:
            print("usage: aisrf-desktop [--port N] [--no-window] [--no-browser]")
            return
        if arg == "--no-window":
            open_window = False
        elif arg == "--no-browser":
            open_browser = False
        elif arg == "--port" and i + 1 < len(args):
            port = int(args[i + 1])
            i += 1
        elif arg.startswith("--port="):
            port = int(arg.split("=", 1)[1])
        else:
            print(f"unknown argument: {arg}", file=sys.stderr)
            sys.exit(2)
        i += 1
    sys.exit(run_desktop(port=port, open_window=open_window, open_browser=open_browser))


if __name__ == "__main__":
    main()
