apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aisrf-data
  labels:
    app.kubernetes.io/name: aisrf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard
